/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fsmini;
import java.io.*;
import static fsmini.batch.b1;
import static fsmini.batch.b2;
import static fsmini.batch.b3;
import static fsmini.batch.b4;
import static fsmini.FSmini.s;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author Hiranmayee
 */
public class feepay extends javax.swing.JFrame {

    /** Creates new form feepay */
    public feepay() {
        initComponents();
        this.setSize(1300,900);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        switch(s.batch){
            case "vocal":fee.setText("700");
                        break;
            case "guitar":fee.setText("600");
                        break;
            case "violin":fee.setText("650");
                        break;
            case "flute":fee.setText("800");
                        break;
        }
        
                    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        feep = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        fdone = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("You need to pay the amount shown below");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 59, 1042, 60);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the amount:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 410, 270, 45);

        feep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feepActionPerformed(evt);
            }
        });
        getContentPane().add(feep);
        feep.setBounds(360, 420, 80, 30);

        fee.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        getContentPane().add(fee);
        fee.setBounds(90, 210, 69, 40);

        fdone.setBackground(new java.awt.Color(255, 255, 255));
        fdone.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        fdone.setText("Done");
        fdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdoneActionPerformed(evt);
            }
        });
        getContentPane().add(fdone);
        fdone.setBounds(480, 570, 100, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsmini/Webp.net-resizeimage (7).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1300, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feepActionPerformed

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeActionPerformed

    private void fdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdoneActionPerformed
       
        fsmini.FSmini.check();
         
        home h=new home();
        h.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_fdoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
                

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feepay().setVisible(true);
                            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fdone;
    public static javax.swing.JTextField fee;
    public static javax.swing.JTextField feep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
