/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fsmini;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.*;
/**
 *
 * @author Hiranmayee
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public home() {
        initComponents();
        this.setSize(1300,900);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        payfee = new javax.swing.JButton();
        buysong = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(206, 28, 28));
        jLabel1.setText("You can do:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(74, 75, 255, 60);

        payfee.setBackground(new java.awt.Color(255, 102, 0));
        payfee.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        payfee.setText("Pay fee");
        payfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payfeeActionPerformed(evt);
            }
        });
        getContentPane().add(payfee);
        payfee.setBounds(74, 207, 123, 37);

        buysong.setBackground(new java.awt.Color(255, 102, 0));
        buysong.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        buysong.setText("Buy Karaoke");
        buysong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buysongActionPerformed(evt);
            }
        });
        getContentPane().add(buysong);
        buysong.setBounds(74, 328, 197, 37);

        quit.setBackground(new java.awt.Color(255, 102, 0));
        quit.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        quit.setText("Quit Institution");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit);
        quit.setBounds(74, 450, 229, 37);

        logout.setBackground(new java.awt.Color(255, 102, 0));
        logout.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(74, 574, 131, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsmini/Webp.net-resizeimage (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buysongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buysongActionPerformed
        search s=new search();
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_buysongActionPerformed

    private void payfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payfeeActionPerformed
          
          feepay f=new feepay();
          f.setVisible(true);
          FSmini.packf();// TODO add your handling code here:
    }//GEN-LAST:event_payfeeActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        try{
        FSmini.del();
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_quitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        welcome w=new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buysong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton payfee;
    private javax.swing.JButton quit;
    // End of variables declaration//GEN-END:variables
}
