/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fsmini;
import fsmini.FSmini;
import java.io.*;
import java.util.*;
import java.awt.*;
/**
 *
 * @author Hiranmayee
 */
public class register extends javax.swing.JFrame {

    /** Creates new form register */
    public register() {
        initComponents();
        this.setSize(1300,900);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stname = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        rnext = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register here");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 80, 350, 70);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 240, 70, 31);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Whatsapp number:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 340, 186, 30);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Set Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 440, 140, 30);
        getContentPane().add(stname);
        stname.setBounds(320, 230, 230, 30);

        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        getContentPane().add(phno);
        phno.setBounds(320, 340, 230, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(320, 440, 230, 30);

        rnext.setBackground(new java.awt.Color(255, 255, 255));
        rnext.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        rnext.setText("Next");
        rnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnextActionPerformed(evt);
            }
        });
        getContentPane().add(rnext);
        rnext.setBounds(250, 600, 100, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsmini/Webp.net-resizeimage (3).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1300, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void rnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnextActionPerformed

        batch b=new batch();
            b.setVisible(true);
    }//GEN-LAST:event_rnextActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FSmini fs1=new FSmini();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPasswordField password;
    public static javax.swing.JTextField phno;
    private javax.swing.JButton rnext;
    public static javax.swing.JTextField stname;
    // End of variables declaration//GEN-END:variables

}
