/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fsmini;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Hiranmayee
 */
public class songpay extends javax.swing.JFrame {
 
    /**
     * Creates new form songpay
     */
    public songpay() {
        
        initComponents();
       
        this.setSize(1300,900);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sfee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sfeep = new javax.swing.JTextField();
        sdone = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("You need to pay the amount shown below");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 1042, 55);
        getContentPane().add(sfee);
        sfee.setBounds(80, 190, 68, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the amount:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 340, 172, 40);

        sfeep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfeepActionPerformed(evt);
            }
        });
        getContentPane().add(sfeep);
        sfeep.setBounds(300, 340, 70, 30);

        sdone.setBackground(new java.awt.Color(255, 255, 255));
        sdone.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        sdone.setText("Done");
        sdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdoneActionPerformed(evt);
            }
        });
        getContentPane().add(sdone);
        sdone.setBounds(210, 500, 110, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fsmini/Webp.net-resizeimage (5).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1300, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdoneActionPerformed
    
        FSmini.costcheck();
        home h=new home();
        h.setVisible(true);
    }//GEN-LAST:event_sdoneActionPerformed

    private void sfeepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfeepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfeepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(songpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(songpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(songpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(songpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new songpay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JButton sdone;
    public static javax.swing.JTextField sfee;
    public static javax.swing.JTextField sfeep;
    // End of variables declaration//GEN-END:variables
}
